"""Out-of-sample verification of the discovered sigma-form ODE, and the
asymptotic recursion it implies.

The relation was found by nullspace search in sigma_ode.py over s in [1,4].
Nothing here re-uses those samples.  Confirmation points are chosen at large
s, far outside the discovery window, because a relation that held only where
it was fitted would be an interpolation artefact -- the same failure mode as
L-030, where a law was read off the lattice that produced it.

DISCOVERED RELATION (sigma_ode.py, 6 exact dyadic coefficients out of 70
monomials, all 64 others at noise ~1e-49):

    s^2 sigma''^2 + 16 u^2 + 4 u sigma'^2 = 0,      u = s sigma' - sigma

If this holds out of sample, the asymptotic tail of log det is generated by
recursion, and E1 stops being a fitted nuisance.
"""

from __future__ import annotations

import json
import sys

from mpmath import mp

from sigma_ode import sigma_data


def residual(s, n):
    """R and a scale for it, so the ratio is meaningful."""
    sig, sig1, sig2 = sigma_data(s, n)
    u = s * sig1 - sig
    t1 = s ** 2 * sig2 ** 2
    t2 = 16 * u ** 2
    t3 = 4 * u * sig1 ** 2
    R = t1 + t2 + t3
    scale = max(abs(t1), abs(t2), abs(t3))
    return R, scale, (sig, sig1, sig2)


def main():
    dps = int(sys.argv[1]) if len(sys.argv) > 1 else 80
    mp.dps = dps
    print(f"[cfg] dps={dps}  discovery window was s in [1,4]")
    print(f"{'s':>8} {'nodes':>6} {'|R|/scale':>14}  {'sigma':>26}")

    rows = []
    # Deliberately outside [1,4], including s far above it.
    for s_int, n in [(6, 60), (9, 70), (12, 80), (20, 110), (30, 150)]:
        s = mp.mpf(s_int)
        R, scale, vals = residual(s, n)
        rel = abs(R) / scale
        rows.append({"s": s_int, "n": n,
                     "log10_rel_residual": float(mp.log10(rel)) if rel > 0 else None,
                     "sigma": mp.nstr(vals[0], 30)})
        print(f"{s_int:>8} {n:>6} {mp.nstr(rel, 6):>14}  {mp.nstr(vals[0], 26):>26}")

    # Control: the same functional with a deliberately wrong coefficient.
    # If this also returns ~0 the test has no resolution (L-024's rule:
    # a control must be validated against its own resolution).
    print("\n[control] same points, coefficient 16 -> 16.0000000001")
    for s_int, n in [(9, 70), (20, 110)]:
        s = mp.mpf(s_int)
        sig, sig1, sig2 = sigma_data(s, n)
        u = s * sig1 - sig
        t1 = s ** 2 * sig2 ** 2
        t2 = mp.mpf("16.0000000001") * u ** 2
        t3 = 4 * u * sig1 ** 2
        rel = abs(t1 + t2 + t3) / max(abs(t1), abs(t2), abs(t3))
        print(f"{s_int:>8} {n:>6} {mp.nstr(rel, 6):>14}   <- must be >> the row above")

    with open("out/sigma_ode_verify.json", "w") as fh:
        json.dump({"dps": dps, "rows": rows}, fh, indent=2)
    print("\n[out] out/sigma_ode_verify.json")


if __name__ == "__main__":
    main()
